common: &defaults
  adapter:  postgresql
  encoding: unicode
  database: rails4_<%= Rails.env %>
  pool:     5
  username: rails4
  password:

development:
  <<: *defaults

test:
  <<: *defaults

cucumber:
  <<: *defaults

production:
  <<: *defaults
  database: rails4

